// const indiGo = "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/6E.png"
// const vistara = "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/UK.png"
// const spiceJet = "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/SG.png"
// const airIndia = "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/AI.png"
// const airIndiaExp = "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/I5.png"

export const airlineData = {
  "65144a1b664a43628887c460": {
    airline_name: "IndiGo Flights",
    logo: "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/6E.png",
  },
  "65144a1b664a43628887c45f": {
    airline_name: "Air Vistara",
    logo: "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/UK.png",
  },
  "65144a1b664a43628887c45e": {
    airline_name: "Spice Jet",
    logo: "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/SG.png",
  },
  "65144a1b664a43628887c461": {
    airline_name: "Air India",
    logo: "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/AI.png",
  },
  "65144a1b664a43628887c45d": {
    airline_name: "Air India Express",
    logo: "https://imgak.goibibo.com/flights-gi-assets/images/v2/app-img/I5.png",
  },
};

export const cityData = {
  "HYD": {
    name: "Rajiv Gandhi International Airport",
    city: "Hyderabad",
    country: "India",
  },
  "AMD": {
    name: "Sardar Vallabhbhai Patel International Airport",
    city: "Ahmedabad",
    country: "India",
  },
  "GOI": {
    name: "Goa International Airport",
    city: "Goa",
    country: "India",
  },
  "PNQ": {
    name: "Pune Airport",
    city: "Pune",
    country: "India",
  },
  "GAU": {
    name: "Lokpriya Gopinath Bordoloi International Airport",
    city: "Guwahati",
    country: "India",
  },
  "JAI": {
    name: "Jaipur International Airport",
    city: "Jaipur",
    country: "India",
  },
  "NAG": {
    name: "Dr. Babasaheb Ambedkar International Airport",
    city: "Nagpur",
    country: "India",
  },
  "DEL": {
    name: "Indira Gandhi International Airport",
    city: "Delhi",
    country: "India",
  },
  "BOM": {
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
    country: "India",
  },
  "BLR": {
    name: "Kempegowda International Airport",
    city: "Bengaluru",
    country: "India",
  },
  "CCU": {
    name: "Netaji Subhas Chandra Bose International Airport",
    city: "Kolkata",
    country: "India",
  },
  "MAA": {
    name: "Chennai International Airport",
    city: "Chennai",
    country: "India",
  },
  "COK": {
    name: "Cochin International Airport",
    city: "Kochi",
    country: "India",
  },
  "IXC": {
    name: "Chandigarh International Airport",
    city: "Chandigarh",
    country: "India",
  },
  "BBI": {
    name: "Biju Patnaik International Airport",
    city: "Bhubaneswar",
    country: "India",
  },
  "CJB": {
    name: "Coimbatore International Airport",
    city: "Coimbatore",
    country: "India",
  },
  "LKO": {
    name: "Lucknow International Airport",
    city: "Lucknow",
    country: "India",
  },
  "TRV": {
    name: "Trivandrum International Airport",
    city: "Thiruvananthapuram",
    country: "India",
  },
  "IXE": {
    name: "Mangalore International Airport",
    city: "Mangalore",
    country: "India",
  },
  "ATQ": {
    name: "Amritsar International Airport",
    city: "Amritsar",
    country: "India",
  },
};

const airportData = [
  {
    _id: "6514309e348f6fafa1b86600",
    name: "Rajiv Gandhi International Airport",
    city: "Hyderabad",
    country: "India",
    iata_code: "HYD",
    icao_code: "VOHS",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86601",
    name: "Sardar Vallabhbhai Patel International Airport",
    city: "Ahmedabad",
    country: "India",
    iata_code: "AMD",
    icao_code: "VAAH",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86602",
    name: "Goa International Airport",
    city: "Goa",
    country: "India",
    iata_code: "GOI",
    icao_code: "VOGO",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86603",
    name: "Pune Airport",
    city: "Pune",
    country: "India",
    iata_code: "PNQ",
    icao_code: "VAPO",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86604",
    name: "Lokpriya Gopinath Bordoloi International Airport",
    city: "Guwahati",
    country: "India",
    iata_code: "GAU",
    icao_code: "VEGT",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86605",
    name: "Jaipur International Airport",
    city: "Jaipur",
    country: "India",
    iata_code: "JAI",
    icao_code: "VIJP",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86606",
    name: "Dr. Babasaheb Ambedkar International Airport",
    city: "Nagpur",
    country: "India",
    iata_code: "NAG",
    icao_code: "VANP",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86607",
    name: "Indira Gandhi International Airport",
    city: "Delhi",
    country: "India",
    iata_code: "DEL",
    icao_code: "VIDP",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86608",
    name: "Chhatrapati Shivaji Maharaj International Airport",
    city: "Mumbai",
    country: "India",
    iata_code: "BOM",
    icao_code: "VABB",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86609",
    name: "Kempegowda International Airport",
    city: "Bengaluru",
    country: "India",
    iata_code: "BLR",
    icao_code: "VOBL",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b8660a",
    name: "Netaji Subhas Chandra Bose International Airport",
    city: "Kolkata",
    country: "India",
    iata_code: "CCU",
    icao_code: "VECC",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b8660b",
    name: "Chennai International Airport",
    city: "Chennai",
    country: "India",
    iata_code: "MAA",
    icao_code: "VOMM",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b8660c",
    name: "Cochin International Airport",
    city: "Kochi",
    country: "India",
    iata_code: "COK",
    icao_code: "VOCI",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b8660d",
    name: "Chandigarh International Airport",
    city: "Chandigarh",
    country: "India",
    iata_code: "IXC",
    icao_code: "VICG",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b8660e",
    name: "Biju Patnaik International Airport",
    city: "Bhubaneswar",
    country: "India",
    iata_code: "BBI",
    icao_code: "VEBS",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b8660f",
    name: "Coimbatore International Airport",
    city: "Coimbatore",
    country: "India",
    iata_code: "CJB",
    icao_code: "VOCB",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86610",
    name: "Lucknow International Airport",
    city: "Lucknow",
    country: "India",
    iata_code: "LKO",
    icao_code: "VILK",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86611",
    name: "Trivandrum International Airport",
    city: "Thiruvananthapuram",
    country: "India",
    iata_code: "TRV",
    icao_code: "VOTV",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86612",
    name: "Mangalore International Airport",
    city: "Mangalore",
    country: "India",
    iata_code: "IXE",
    icao_code: "VOML",
    __v: 0,
  },
  {
    _id: "6514309e348f6fafa1b86613",
    name: "Amritsar International Airport",
    city: "Amritsar",
    country: "India",
    iata_code: "ATQ",
    icao_code: "VIAR",
    __v: 0,
  },
];
